replicaCount: 1

image:
  repository: quay.io/commonwl/cwltool  # Docker image for cwltool
  tag: latest               # Image tag
  pullPolicy: IfNotPresent  # Image pull policy

workflow:
  workflowFile: workflow.cwl # Default workflow file name
  jobFile: job.yaml         # Default job file name

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

volume:
  mountPath: /data
  usePersistentVolume: false # Set to true to use PVC
  hostPath: /path/to/workflows # Use HostPath if PVC is not enabled
  storageSize: 1Gi            # Size of PVC (if enabled)
