apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-workflow-config
data:
  {{ .Values.workflow.workflowFile }}: |
    # Add your CWL workflow content here
  {{ .Values.workflow.jobFile }}: |
    # Add your CWL job file content here
