apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cwltool
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: cwltool
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - cwltool
            - /data/{{ .Values.workflow.workflowFile }}
            - /data/{{ .Values.workflow.jobFile }}
          volumeMounts:
            - name: workflow-volume
              mountPath: {{ .Values.volume.mountPath }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
      volumes:
        - name: workflow-volume
          {{- if .Values.volume.usePersistentVolume }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
          {{- else }}
          hostPath:
            path: {{ .Values.volume.hostPath }}
          {{- end }}
